Reformat all scripts

diff --git a/rf b/rf
--- a/rf
+++ b/rf
@@ -4,33 +4,33 @@
 # This would be in .bashrc but I want KRunner to be able to run it
 
 case "$1" in
-    cd*)
-      cCode="05"
-      cName="Neilson"
-      ;;
-    br*)
-      cCode="01"
-      cName="Brower"
-      ;;
-    b*)
-      cCode="04"
-      cName="Busch"
-      ;;
-    l*)
-      cCode="03"
-      cName="Livi"
-      ;;
-    *)
-      echo "INVALID CAMPUS. Please specify cd, br, b, or l (Cook/Douglass, Brower, Busch, Livingston)."
-      exit 1
-      ;;
+cd*)
+  cCode="05"
+  cName="Neilson"
+  ;;
+br*)
+  cCode="01"
+  cName="Brower"
+  ;;
+b*)
+  cCode="04"
+  cName="Busch"
+  ;;
+l*)
+  cCode="03"
+  cName="Livi"
+  ;;
+*)
+  echo "INVALID CAMPUS. Please specify cd, br, b, or l (Cook/Douglass, Brower, Busch, Livingston)."
+  exit 1
+  ;;
 esac
 
 case "$2" in
-  b) mealName="Breakfast";;
-  l) mealName="Lunch";;
-  d) mealName="Dinner";;
-  t) mealName="Knight Room";;
+b) mealName="Breakfast" ;;
+l) mealName="Lunch" ;;
+d) mealName="Dinner" ;;
+t) mealName="Knight Room" ;;
 esac
 
 # It's okay to include "&mealName=" without specifying a campus; looks like FoodPro just ignores it
diff --git a/yaud b/yaud
--- a/yaud
+++ b/yaud
@@ -1,56 +1,56 @@
 #!/bin/bash
 
-function showHelp {
-    printf "Usage: yaud [OPTION] [URL]\n"
-    printf "Download the best-quality audio version of something with youtube-dl.\n"
-    printf "If the downloaded file is a video, extract the audio with ffmpeg.\n\n"
-    printf "  -k, --keep	Don't delete original video file after conversion\n"
-    printf "  -h, --help	Show this help message\n"
+function showHelp() {
+  printf "Usage: yaud [OPTION] [URL]\n"
+  printf "Download the best-quality audio version of something with youtube-dl.\n"
+  printf "If the downloaded file is a video, extract the audio with ffmpeg.\n\n"
+  printf "  -k, --keep	Don't delete original video file after conversion\n"
+  printf "  -h, --help	Show this help message\n"
 }
 
 ################################################################ Argument validation
 # Check if user passed --help or --keep
 # Also figure out which arg is the URL
 for arg in "$@"; do
-    if [[ "$arg" = -h ]] || [[ "$arg" = --help ]]; then
-        showHelp
-        exit 0
-    elif [[ "$arg" = -k ]] || [[ "$arg" = --keep ]]; then
-        keep=1
-    elif [[ "$arg" == -* ]]; then
-        printf "ERROR: Unrecognized option \"$arg\"\n\n"
-        showHelp
-        exit 1
-    else
-        url_arg="$arg"
-        ((urls++))
-    fi
+  if [[ "$arg" == -h ]] || [[ "$arg" == --help ]]; then
+    showHelp
+    exit 0
+  elif [[ "$arg" == -k ]] || [[ "$arg" == --keep ]]; then
+    keep=1
+  elif [[ "$arg" == -* ]]; then
+    printf "ERROR: Unrecognized option \"$arg\"\n\n"
+    showHelp
+    exit 1
+  else
+    url_arg="$arg"
+    ((urls++))
+  fi
 done
 
 if [[ ! $# =~ [1-2] ]]; then
-    if [[ $# > 2 ]]; then
-        printf "ERROR: Too many arguments provided\n\n"
-    fi
-    showHelp
-    exit 1
+  if [[ $# > 2 ]]; then
+    printf "ERROR: Too many arguments provided\n\n"
+  fi
+  showHelp
+  exit 1
 fi
 
 if [[ $urls > 1 ]]; then
-    printf "ERROR: multiple arguments provided for URL\n\n"
-    showHelp
-    exit 1
+  printf "ERROR: multiple arguments provided for URL\n\n"
+  showHelp
+  exit 1
 fi
 
 if [[ -z $url_arg ]]; then
-    printf "ERROR: no URL provided\n\n"
-    showHelp
-    exit 1
+  printf "ERROR: no URL provided\n\n"
+  showHelp
+  exit 1
 fi
 
 ################################################################ Check for youtube-dl
-if ! command -v youtube-dl > /dev/null 2>&1; then
-    printf 'ERROR: youtube-dl not found in $PATH\n'
-    exit 1
+if ! command -v youtube-dl >/dev/null 2>&1; then
+  printf 'ERROR: youtube-dl not found in $PATH\n'
+  exit 1
 fi
 
 ################################################################ Download audio
@@ -63,40 +63,40 @@ songname=$(printf "$ytdl_output" | grep Destination)
 songname=${songname##*: }
 
 if [ "$songname" = "" ]; then
-    # Okay, get the *actual* line with the filename
-    songname=$(printf "$ytdl_output" | grep "already")
-    songname=${songname#* }
-    songname=${songname% has already been downloaded}
-    printf "\nDownload failed"
-    if [[ -e "$songname" ]]; then
-        printf ', because file already exists. Continue? (y/n) '
-        read answer
-        if [[ "$answer" != "y" ]] && [[ "$answer" != "yes" ]]; then
-            exit 0
-        fi
-    else
-        printf "\nERROR: Cannot continue without file\n"
-        exit 1
+  # Okay, get the *actual* line with the filename
+  songname=$(printf "$ytdl_output" | grep "already")
+  songname=${songname#* }
+  songname=${songname% has already been downloaded}
+  printf "\nDownload failed"
+  if [[ -e "$songname" ]]; then
+    printf ', because file already exists. Continue? (y/n) '
+    read answer
+    if [[ "$answer" != "y" ]] && [[ "$answer" != "yes" ]]; then
+      exit 0
     fi
+  else
+    printf "\nERROR: Cannot continue without file\n"
+    exit 1
+  fi
 else
-    printf "Downloaded $songname\n\n"
+  printf "Downloaded $songname\n\n"
 fi
 
 song_ext=${songname##*.}
 
 # If the file isn't a video, we're done
 if [[ "$songname" != *.webm ]] && [[ "$songname" != *.mp4 ]]; then
-    printf "Success!\n"
-    exit 0
+  printf "Success!\n"
+  exit 0
 fi
 
 ################################################################ Fix container if needed
 printf "File extension is .$song_ext. Attempting conversion...\n\n"
 
-if ! command -v ffmpeg > /dev/null 2>&1; then
-    printf 'ERROR: ffmpeg not found in $PATH\n'
-    printf "Could not extract audio\n"
-    exit 1
+if ! command -v ffmpeg >/dev/null 2>&1; then
+  printf 'ERROR: ffmpeg not found in $PATH\n'
+  printf "Could not extract audio\n"
+  exit 1
 fi
 
 ffprobe_output=$(ffmpeg -i "$songname" 2>&1 | grep "Audio")
@@ -112,19 +112,19 @@ new_type=${new_type%% *}
 printf "Actual audio type is \"$new_type\"\n\n"
 
 case $new_type in
-    opus)
-        new_ext=opus
-        ;;
-    vorbis)
-        new_ext=ogg
-        ;;
-    aac)
-        new_ext=aac
-        ;;
-    *)
-        printf "ERROR: Could not determine proper file extension\n"
-        exit 1
-        ;;
+opus)
+  new_ext=opus
+  ;;
+vorbis)
+  new_ext=ogg
+  ;;
+aac)
+  new_ext=aac
+  ;;
+*)
+  printf "ERROR: Could not determine proper file extension\n"
+  exit 1
+  ;;
 esac
 
 base_name=${songname%$song_ext}
@@ -135,10 +135,10 @@ printf "Writing to $final_name\n\n"
 ffmpeg -v 24 -i "$songname" -vn -acodec copy "$final_name"
 
 if [[ "$keep" != 1 ]]; then
-    printf "Removing original video file\n"
-    rm "$songname"
+  printf "Removing original video file\n"
+  rm "$songname"
 else
-    printf "Not removing original video file\n"
+  printf "Not removing original video file\n"
 fi
 
 printf "Success!\n"
